[project]
name = "imgapi"
version = "0.1.0"
description = "A simple random image API written in Flask"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "user-agents"
]
